import Head from 'next/head'
import AboutMe from '../components/AboutMe.js/AboutMe'
import IntroSection from '../components/IntroSection/IntroSection'
import WorkAndEducationContainer from '../components/WorkAndEducation/WorkAndEducationContainer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"></link>
      </Head>

     <IntroSection />
     <AboutMe />
     <WorkAndEducationContainer />

    </div>
  )
}
