import Head from "next/head";
import AboutMe from "../components/AboutMe.js/AboutMe";
import IntroSection from "../components/IntroSection/IntroSection";
import WorkAndEducationContainer from "../components/WorkAndEducation/WorkAndEducationContainer";
import ProjectContainer from "../components/Projects/ProjectContainer";
import data from "../ProjectsData/data";
import Container from "../components/Container";

export default function Home({ projects }) {
  return (
    <div>
      <Head>
        <title>Eradiri Richard Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <Container>
        <IntroSection />
        <AboutMe />
        <ProjectContainer projects={projects} />
        <WorkAndEducationContainer />
      </Container>
    </div>
  );
}

export async function getStaticProps() {
  const projects = data;

  return {
    props: { projects },
  };
}
